// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djkbkbhgmoharyhrgasf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqa2JrYmhnbW9oYXJ5aHJnYXNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjA0MDUsImV4cCI6MjA3MTQzNjQwNX0.uI6RnJLMy3TbZC0bRz015VPsqcm685tLxzV9mDe69lY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});