package com.qyk.app.quotes

import android.content.Context
import kotlin.random.Random

object QuoteRepository {
    private const val PREFS = "qyk_quotes_prefs"
    private const val KEY_ORDER = "order"
    private const val KEY_POS = "position"
    private const val KEY_COUNT = "count"

    // Source list of daily Qyk Quotes (check-in prompts)
    private val QUOTES: List<String> = listOf(
        "You’ve made it this far, and that says something about your resilience. What part of you feels tired but still chooses to keep going?",
        "Today is another chance, not a repeat of yesterday. Which thought from yesterday are you willing to release?",
        "You’re carrying more than most people realize. What weight are you silently holding that deserves acknowledgment?",
        "It’s okay if the small steps feel invisible. What’s a tiny action you took today that your future self might thank you for?",
        "Rest is productive when your body asks for it. How do you know when you’re pushing beyond your limit?",
        "You’ve survived every overwhelming moment so far. Which survival skill still serves you, and which one feels outdated?",
        "Your emotions are signals, not enemies. What message might your current mood be trying to send?",
        "Growth often feels like discomfort in disguise. What feels uncomfortable right now but might actually be progress?",
        "You don’t have to be “fine” all the time. What would honesty look like if you answered someone’s “how are you” right now?",
        "Healing rarely looks linear. What pattern do you notice when you circle back to old wounds?",
        "You’ve learned lessons you didn’t ask for. Which one do you wish you could have learned differently?",
        "Quiet moments can be the loudest. What’s the thought that keeps echoing when everything else goes silent?",
        "Your boundaries are proof of self-respect. Where have you noticed yourself slipping on enforcing them?",
        "Being human means being layered. Which layer of you feels unseen today?",
        "Not every day has to be a breakthrough. What’s the smallest shift you’d be content with today?",
        "Your body remembers even what your mind forgets. Where in your body are you holding tension right now?",
        "Restlessness is a teacher, too. What do you think your restlessness is trying to protect you from?",
        "You’ve handled more than you give yourself credit for. What’s one situation you didn’t think you’d get through but did?",
        "Your younger self would be amazed at your survival. What would you want to tell them about who you are now?",
        "Change often starts in quiet rebellion. What’s a rule or expectation you’ve outgrown but still follow out of habit?",
        "Peace doesn’t mean silence—it means alignment. Where in your life do things feel loudest right now?",
        "Your pace is valid, no matter how slow it feels. Where do you feel pressured to rush?",
        "You don’t have to justify your needs. Which need feels hardest for you to admit out loud?",
        "Some days survival is the achievement. What survival strategy do you use most often, and does it still serve you?",
        "You’re not behind—your timeline is your own. Where are you comparing yourself the most lately?",
        "It’s okay to not want to be okay today. What’s the hardest feeling for you to sit with without distraction?",
        "You deserve space to be complicated. What contradiction about yourself do you struggle to accept?",
        "Your story matters, even if no one else hears it. What part of your story feels hardest to share?",
        "Small joys are valid medicine. What overlooked joy has helped you lately?",
        "Your worth isn’t tied to output. When do you notice yourself measuring worth by productivity?",
        "You’ve unlearned things that once felt permanent. What belief no longer fits you?",
        "Sometimes numbness is protection. What might your numbness be shielding you from?",
        "You deserve kindness from yourself, too. What’s one thing you’d never say to a friend but often say to yourself?",
        "Not every thought deserves belief. Which thought has been most persistent, and do you believe it’s true?",
        "You are proof of persistence. Which battle do you still fight daily that no one sees?",
        "Healing takes grief, too. What loss have you never fully allowed yourself to grieve?",
        "Some patterns repeat until you face them. Which one keeps showing up for you?",
        "You can be strong and still need help. Where do you most resist reaching out?",
        "Your silence can say more than your words. What do you wish someone could understand without you saying it?",
        "Even broken things have value. What part of you feels cracked but still functions?",
        "You’ve adapted through necessity. Which adaptation feels least authentic to who you really are?",
        "Rest is resistance in a world that glorifies exhaustion. What kind of rest feels least accessible to you?",
        "You deserve to exist without performance. Where in your life do you feel most like you’re acting?",
        "Some wounds don’t close, but they stop bleeding. Which one still aches but no longer defines you?",
        "Your inner world deserves your attention. What thought loop have you been caught in lately?",
        "Sometimes stillness is where you find yourself again. What keeps you from being still?",
        "Your pain is real, even if unseen. Where do you minimize your pain for others’ comfort?",
        "You’ve learned survival, but have you learned safety? What does safety look like for you now?",
        "Change is proof of life. Which recent change felt both terrifying and freeing?",
        "You’re not alone in feeling alone. When do you feel most disconnected from others?",
        "Every scar carries context. Which scar still feels misunderstood?",
        "Hope can coexist with despair. Where do you see a flicker of hope despite exhaustion?",
        "You’re not defined by your lowest moment. Which moment do you unfairly use as evidence against yourself?",
        "Even uncertainty is a teacher. What’s the hardest unknown you’re sitting with right now?",
        "You’re allowed to question your beliefs. Which belief feels shaky but hard to let go of?",
        "Some days your body speaks louder than your mind. What is it saying today?",
        "You’re here, and that matters. What makes existing feel heavier than living right now?",
        "Healing can feel boring, but it’s happening. What routine feels healing without you noticing?",
        "You’ve become someone past-you couldn’t imagine. How do you think they’d see you today?",
        "Your struggles don’t erase your brilliance. Where do you shine when no one’s looking?",
        "Vulnerability isn’t weakness—it’s courage. What scares you most about being seen fully?",
        "Rest doesn’t require earning. Where do you feel guilty for slowing down?",
        "Sometimes laughter is survival, too. What’s the last thing that made you genuinely laugh?",
        "You’re not too much—you’re carrying too much. What’s one thing you wish you could set down?",
        "It’s okay if your goals shifted. Which old goal no longer feels aligned with who you are?",
        "You deserve gentleness. Where in your life are you most harsh with yourself?",
        "Even silence is communication. What are you not saying out loud right now?",
        "You’re stronger than the voice that says you’re not. What’s the cruelest thought you’ve believed recently?",
        "Healing requires honesty. What truth about yourself feels hardest to admit?",
        "You’ve survived a thousand endings. What new beginning scares you the most?",
        "Your emotions are proof you’re alive. Which one feels hardest to regulate?",
        "It’s okay to let things go unfinished. What are you holding onto that drains you more than it sustains you?",
        "You’re worthy of existing even on your quietest days. When do you feel invisible?",
        "Small acts of care add up. What’s one you’ve neglected lately?",
        "You don’t need to be understood by everyone. Who do you most wish could understand you?",
        "You’ve come back from dark places before. What anchor helped you last time?",
        "Your restlessness is asking for expression. What haven’t you created or released yet?",
        "Even your mistakes carry wisdom. What’s one mistake you still punish yourself for?",
        "You’ve learned to protect yourself. Which defense feels most exhausting now?",
        "Joy is allowed, even in pain. Where does joy sneak in unexpectedly for you?",
        "Your resilience isn’t proof you deserved the hardship. What lesson did you never deserve to learn the hard way?",
        "You’ve changed in ways you don’t always notice. Who would be most surprised by who you are now?",
        "Sometimes survival looks like withdrawal. Where are you hiding, and why?",
        "You’re allowed to not know the answer. What question about your life feels the loudest right now?",
        "Your dreams don’t have expiration dates. Which dream feels neglected but not dead?",
        "You’ve made space for others. Where do you feel most unseen in return?",
        "Healing is slow because you’re thorough. What detail about your growth would others overlook?",
        "You’re more than your coping skills. Which one feels like a crutch now?",
        "It’s okay if you’re still figuring it out. What decision do you feel pressured to rush?",
        "You’re a work in progress, not a failure. What unfinished part of you do you avoid looking at?",
        "Sometimes comfort is found in rituals. What ritual keeps you grounded?",
        "You’ve learned to move through fear. What fear still feels paralyzing?",
        "You’re proof of adaptation. Which adaptation feels like betrayal to yourself?",
        "Your feelings don’t need justification. Which one do you struggle to explain to others?",
        "Healing asks for patience. Where do you feel most impatient with yourself?",
        "You’ve carried parts of others inside you. Which influence do you wish you could shed?",
        "Rest isn’t laziness—it’s repair. Where do you most need repair?",
        "You’re enough, even without evidence. What evidence do you keep demanding from yourself?",
        "Even shadows prove the presence of light. What shadow of yours feels scariest to face?",
        "You’ve outgrown parts of yourself. Which one do you miss, even if it wasn’t healthy?",
        "You’re capable of rewriting your story. Which chapter feels hardest to revisit?",
        "Sometimes stillness is bravery. What are you afraid will surface if you slow down?",
        "You’re human, not a machine. When did you last allow yourself to fully rest?",
        "Even contradictions make sense in context. Which contradiction feels most true about you?",
        "You’ve been both fragile and unbreakable. Which role feels more familiar lately?",
        "You’re worthy of your own compassion. Where do you withhold it the most?",
        "Sometimes progress looks like rest, not movement. What pause have you been resisting?",
        "You’ve become an expert in masking. What truth hides beneath your mask?",
        "Your scars prove survival, not weakness. Which one do you wish people could see differently?",
        "Even your uncertainty is part of the path. What’s the most confusing crossroad you’re at right now?",
        "You’re worthy of being loved as you are. Where do you feel most conditional love?",
        "Some lessons only arrive in hindsight. Which one do you see more clearly now?",
        "You’ve built resilience out of necessity. Where do you long for softness instead?",
        "You’re still here, and that’s enough. What’s one reason you keep showing up?",
        "You’ve adapted to survive, but what about to thrive? What would thriving look like for you?",
        "You’ve hidden parts of yourself to stay safe. Which one is asking to be seen now?",
        "Sometimes numbness feels safer than pain. What would happen if you let yourself feel more fully?",
        "You’re worthy of taking up space. Where do you shrink yourself most?",
        "Even your doubts deserve curiosity. Which doubt feels most persistent?",
        "You’ve made peace with some storms. Which storm still feels unfinished?",
        "Your feelings are not inconveniences. Where do you minimize them most?",
        "You’ve been carrying questions for years. Which one still aches unanswered?",
        "Your survival is not the whole story. What would thriving add to your narrative?",
        "Sometimes the strongest act is surrender. What have you been refusing to release?",
        "You’ve learned to read between the lines. What silence from others feels loudest?",
        "Your future isn’t set in stone. What possibility feels both terrifying and exciting?",
        "You’re not alone in your complexity. Which part of your complexity feels misunderstood?",
        "You’ve made it through 100% of your worst days. What do you fear wouldn’t survive the next one?",
        "You’re worthy of curiosity, even about yourself. What question about yourself are you avoiding?",
        "You’ve felt both hope and hopelessness. Which one feels heavier lately?",
        "You deserve to feel safe in your body. Where does safety feel missing?",
        "You’re allowed to want more. What desire do you silence most often?",
        "Your instincts are shaped by survival. Which instinct feels outdated now?",
        "You’ve survived, but have you healed? Where do you see the difference in yourself?",
        "You’re enough, even unfinished. What unfinished part of you do you still criticize?",
        "Your memories don’t define your worth. Which memory still dictates your self-view?",
        "You’re worthy of belonging. Where do you feel most out of place?",
        "You’ve changed in ways you may not notice. Who would recognize those changes the most?",
        "You deserve to rest without guilt. What guilt do you carry when you rest?",
        "Your softness is strength, too. Where do you hide softness most?",
        "You’re worthy of joy, not just survival. What joy feels hardest to allow right now?",
        "You’ve been shaped by hardship. Which part of you feels strongest because of it?",
        "You’re not broken—you’re adapting. What adaptation feels hardest to undo?",
        "You’re alive, and that matters. What makes being alive feel complicated right now?",
        "Your voice matters. What’s the hardest thing for you to say out loud?",
        "You’ve held others up when you were falling. Who holds you when you break?",
        "You’ve lived through contradictions. Which one defines you most lately?",
        "You deserve the same empathy you give. Where do you withhold it from yourself?",
        "Your path doesn’t need validation. Where do you most crave approval?",
        "You’ve carried burdens you didn’t choose. Which one feels heaviest today?",
        "You’ve survived endings before. Which beginning feels overdue?",
        "You’ve earned your rest. What stops you from fully taking it?",
        "You’ve changed quietly. Which change would shock others if they knew?",
        "You’re worthy of softness in hard places. Where do you wish life was gentler?",
        "You’ve been both resilient and exhausted. Which side shows more now?",
        "You’ve hidden your truth for safety. What truth aches to be spoken?",
        "You’ve adapted again and again. Which adaptation are you most tired of maintaining?",
        "You’re worthy of being heard. Where do you feel silenced most?",
        "You’ve been through storms before. What prepared you the most for the last one?",
        "You’ve felt both belonging and isolation. Which one feels more present now?",
        "You’re worthy of a future that excites you. What vision scares you into stillness?",
        "You’ve survived when you thought you couldn’t. What survival felt most impossible?",
        "You’ve healed in ways unnoticed. What healing would surprise even you?",
        "You’re not your mistakes. Which one still feels like a definition of you?",
        "You’re worthy of patience. Where do you rush yourself most unfairly?",
        "You’ve learned lessons from pain. Which one do you wish had come through love instead?",
        "You’re worthy of your own trust. Where do you doubt yourself most?",
        "You’ve been carrying invisible battles. Which one takes the most energy?",
        "You’ve lived through contradictions. Which one do you still wrestle with?",
        "You’re worthy of existing without performance. What role do you play most reluctantly?",
        "You’ve seen darkness. What small light keeps you moving through it?",
        "You’re not your trauma. What part of yourself feels most untouched by it?",
        "You’re worthy of ease. Where do you complicate things unnecessarily?",
        "You’ve lived through endings. Which one reshaped you most deeply?",
        "You’ve learned to carry silence. What silence is most deafening now?",
        "You’re worthy of connection. Where do you feel most alone?",
        "You’ve learned to keep going. What would stopping look like?",
        "You’re worthy of joy without guilt. What joy feels unsafe to embrace?",
        "You’ve been carrying strength. What’s one thing you wish you didn’t have to be strong for?",
        "You’ve lived with shadows. Which shadow scares you the most?",
        "You’re worthy of self-forgiveness. What do you struggle to forgive yourself for?",
        "You’ve survived. What part of you still feels like it’s fighting daily?",
        "You’re worthy of gentleness. Where do you crave it the most?",
        "You’ve been shaped by struggle. What part of you feels most proud despite it?",
        "You’re worthy of peace. What steals your peace most often?",
        "You’ve carried burdens. What would laying one down feel like?",
        "You’re worthy of being loved fully. What part of you feels hardest to love?",
        "You’ve learned to protect yourself. Where do you long for more openness?",
        "You’re worthy of healing. What does healing still look like for you?"
    )

    fun getNext(context: Context): String {
        val prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        val count = QUOTES.size
        var savedCount = prefs.getInt(KEY_COUNT, -1)
        var order = prefs.getString(KEY_ORDER, null)?.split(',')?.mapNotNull { it.toIntOrNull() }?.toMutableList()
        var pos = prefs.getInt(KEY_POS, 0)

        if (order == null || order.size != count || savedCount != count) {
            order = (0 until count).toMutableList()
            order.shuffle(Random(System.currentTimeMillis()))
            pos = 0
            prefs.edit().putString(KEY_ORDER, order.joinToString(",")).putInt(KEY_POS, pos).putInt(KEY_COUNT, count).apply()
        }

        if (pos >= order.size) {
            order.shuffle(Random(System.currentTimeMillis()))
            pos = 0
        }

        val idx = order[pos]
        val quote = QUOTES[idx]
        prefs.edit().putInt(KEY_POS, pos + 1).putString(KEY_ORDER, order.joinToString(",")).apply()
        return quote
    }
}
